// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_Ap1_Josue_Osorio_2018_0938.DAL;

namespace P2_Ap1_Josue_Osorio_2018_0938.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211110181643_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_Ap1_Josue_Osorio_2018_0938.Entidades.Proyectos", b =>
                {
                    b.Property<int>("Proyectoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Proyectoid");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("P2_Ap1_Josue_Osorio_2018_0938.Entidades.TipoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Proyectoid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipodeTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Proyectoid");

                    b.ToTable("TipoDetalle");
                });

            modelBuilder.Entity("P2_Ap1_Josue_Osorio_2018_0938.Entidades.TipoTarea", b =>
                {
                    b.Property<int>("Tipoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipodeTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("Tipoid");

                    b.ToTable("TipoTarea");

                    b.HasData(
                        new
                        {
                            Tipoid = 1,
                            Tiempo = 0,
                            TipodeTarea = "Analisis"
                        },
                        new
                        {
                            Tipoid = 2,
                            Tiempo = 0,
                            TipodeTarea = "Diseno"
                        },
                        new
                        {
                            Tipoid = 3,
                            Tiempo = 0,
                            TipodeTarea = "Programacion"
                        },
                        new
                        {
                            Tipoid = 4,
                            Tiempo = 0,
                            TipodeTarea = "Prueba"
                        });
                });

            modelBuilder.Entity("P2_Ap1_Josue_Osorio_2018_0938.Entidades.TipoDetalle", b =>
                {
                    b.HasOne("P2_Ap1_Josue_Osorio_2018_0938.Entidades.Proyectos", null)
                        .WithMany("TipoDetalle")
                        .HasForeignKey("Proyectoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P2_Ap1_Josue_Osorio_2018_0938.Entidades.Proyectos", b =>
                {
                    b.Navigation("TipoDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
