// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_Ap1_Josue_Osorio_2018_0938.DAL;

namespace P2_Ap1_Josue_Osorio_2018_0938.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_Ap1_Josue_Osorio_2018_0938.Entidades.TipoTarea", b =>
                {
                    b.Property<int>("Tipoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipodeTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("Tipoid");

                    b.ToTable("TipoDeTarea");

                    b.HasData(
                        new
                        {
                            Tipoid = 1,
                            Tiempo = 0,
                            TipodeTarea = "Analisis"
                        },
                        new
                        {
                            Tipoid = 2,
                            Tiempo = 0,
                            TipodeTarea = "Diseno"
                        },
                        new
                        {
                            Tipoid = 3,
                            Tiempo = 0,
                            TipodeTarea = "Programacion"
                        },
                        new
                        {
                            Tipoid = 4,
                            Tiempo = 0,
                            TipodeTarea = "Prueba"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
